name: Android CI

# secrets accessing referenced from Jake Lee
# https://blog.jakelee.co.uk/accessing-android-app-secret-from-github-actions-using-gradle/

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Access APOD_API_KEY
      env:
        APOD_API_KEY: $
      run: echo APOD_API_KEY=\"$APOD_API_KEY\" > local.properties
    - name: Setup Android SDK Tools
      uses: android-actions/setup-android@v2.0.2
    - name: Create local.properties file
      run: echo "sdk.dir=$ANDROID_HOME" >> local.properties && cat local.properties
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Run unit tests
      run: ./gradlew test  
